permalink: :categories/

# Site settings
lang: ja
title: lela.iúk.tánxe
email: ""
author:
  name: cogas.iuk.uasanbon
  email: cheeky.chic.chick@gmail.com

url: "http://cogas.github.io"

twitter_username: oka_iu_tcan
github_username:  cogas

# Build settings
markdown: kramdown
