permalink: :categories/

# Site settings
lang: ja
title: 生姜の物置き
email: ""
author:
  name: cogas
  email: cheeky.chic.chick@gmail.com

highlighter: pygments
github: [Repository metadata]

url: "http://cogas.github.io"

twitter_username: oka_iu_tcan
github_username:  cogas

# Build settings
markdown: kramdown

