# Site settings
title: My lojban .iu
email: ""
description: > # this means to ignore newlines until "baseurl:"
  coirodo  
  ここはおかゆの運営するロジバンに関するサイトです。

baseurl: "/newjk/myblog" # the subpath of your site, e.g. /blog/
url: "http://cogas.github.io" # the base hostname & protocol for your site
twitter_username: oka_iu_tcan
github_username:  cogas

# Build settings
markdown: kramdown
