permalink: /:categories/:year-:month-:day/:title

# Site settings
title: lo mi lojbo .iu
email: ""
author:
  name: cogas
  email: cheeky.chic.chick@gmail.com

baseurl: "/jk" # the subpath of your site, e.g. /blog/
url: "http://cogas.github.io"

twitter_username: oka_iu_tcan
github_username:  cogas

# Build settings
markdown: kramdown
